name: dev-workflow
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: yarn install --frozen-lockfile
      - run: yarn test-ci
      - run: yarn webpack-prod
        env:
          DEBUG_ON: false
      - run: yarn serve &
      - run: yarn cy-run-ci
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          path: cypress/screenshots/
